source/complete/Yotodo/Models/Todo.cs
using System;

namespace Yotodo.Models
{
    
    public class Todo{
        public Guid Id{get;set;}
        public String Title{get;set;}
        public String Description{get;set;}
        public DateTime? CompletionDate{get;set;}
        public bool IsCompleted{get;set;}
    }
}

source/complete/Yotodo/ViewModels/TodoAddViewModel.cs
using System;

namespace Yotodo.ViewModels
{
    
    public class TodoAddViewModel{
      
        public String Title{get;set;}
        public String Description{get;set;}
    }
}

source/complete/Yotodo/ViewModels/TodoListStatus.cs
namespace Yotodo.ViewModels{
    
    public class TodoListStatus{
        public int Total{get;set;}
        public int Completed{get;set;}
    }
}

source/complete/Yotodo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Yotodo.Data;

namespace Yotodo.Controllers
{
    public class HomeController : Controller
    {
        protected ApplicationDataContext DataContext;
        
        public HomeController(ApplicationDataContext dataContext){
                DataContext = dataContext;
        }
        public IActionResult Index()
        {
           return RedirectToAction("Index", "Todos");
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

source/complete/Yotodo/Controllers/TodosApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Yotodo.Data;
using Yotodo.Models;
using Yotodo.ViewModels;

namespace Yotodo.Controllers
{
    [Route("/api/todos")]
    public class TodosApiController : Controller
    {
        protected ApplicationDataContext DataContext;
        
        public TodosApiController (ApplicationDataContext dataContext){
                DataContext = dataContext;
        }
        
        [HttpGet]
        public IActionResult GetTodos()
        {
            var model = DataContext.Todos.Where(x => x.IsCompleted == false).ToList();
            return Ok(model);
        }
        
        [HttpPost]
        public IActionResult Add([FromBody]TodoAddViewModel model){
            
            if(ModelState.IsValid){
                var entity = new Todo(){
                    Title = model.Title, 
                    Description = model.Description,
                    Id = Guid.NewGuid()
                };
                DataContext.Todos.Add(entity);
                DataContext.SaveChanges();
                
                return Ok(entity);
            }
            
            return HttpBadRequest(ModelState);
        }
        
        [HttpPut("complete/{id}")]
        public IActionResult Complete(Guid id){
            
            var entity = DataContext.Todos.FirstOrDefault(x => x.Id == id);
            
            if(entity == null){
                return HttpBadRequest("Could not find Todo: " + id);
            }
            
            entity.IsCompleted = true;
            entity.CompletionDate = DateTime.UtcNow;
            DataContext.Todos.Update(entity);
            
            DataContext.SaveChanges();
            
            return new NoContentResult();
        }
    }
}

source/complete/Yotodo/Controllers/TodosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Yotodo.Data;
using Yotodo.Models;
using Yotodo.ViewModels;

namespace Yotodo.Controllers
{
    public class TodosController : Controller
    {
        protected ApplicationDataContext DataContext;
        
        public TodosController (ApplicationDataContext dataContext){
                DataContext = dataContext;
        }
        
        public IActionResult Index()
        {
            var model = DataContext.Todos.Where(x => x.IsCompleted == false).ToList();
            
            ViewData.Model = model;
            
            return View();
        }

        [HttpGet]
        public IActionResult Add(){
            ViewData.Model = new TodoAddViewModel();
            return View();
        }
        
        [HttpPost]
        public IActionResult Add(TodoAddViewModel model){
            
            if(ModelState.IsValid){
                var entity = new Todo(){
                    Title = model.Title, 
                    Description = model.Description,
                    Id = Guid.NewGuid()
                };
                DataContext.Todos.Add(entity);
                DataContext.SaveChanges();
                
                return RedirectToAction("Index", "Home");
            }
            
            return View(model);
        }
        
        [HttpPut("/todos/complete/{id}")]
        public IActionResult Complete(Guid id){
            
            var entity = DataContext.Todos.FirstOrDefault(x => x.Id == id);
            
            if(entity == null){
                return HttpBadRequest("Could not find Todo: " + id);
            }
            
            entity.IsCompleted = true;
            entity.CompletionDate = DateTime.UtcNow;
            DataContext.Todos.Update(entity);
            
            DataContext.SaveChanges();
            
            return new NoContentResult();
        }
        
        [HttpGet("/todos/spa")]
        public IActionResult Spa(){
            return View();
        }
    }
}

source/complete/Yotodo/ViewComponents/TodoStatusViewComponent.cs
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Yotodo.Data;
using Yotodo.Models;
using Yotodo.Services;
using Yotodo.ViewModels;


namespace Yotodo.ViewComponents
{
    public class TodoStatusViewComponent : ViewComponent
    {
        private readonly ApplicationDataContext _context;

        // public TodoStatusViewComponent(ApplicationDataContext context)
        // {
        //     _context = context;
        // }
        
        private IStatisticsService _service;
        
        public TodoStatusViewComponent(IStatisticsService service)
        {
            _service = service;
        }

        public async Task<IViewComponentResult> InvokeAsync(bool isComplete)
        {
            var items = await GetItemsAsync(isComplete);
            return View(items);
        }
        
        private async Task<TodoListStatus> GetItemsAsync(bool isComplete)
        {
            // var total = await _context.Todos.CountAsync();
            // var completed = await _context.Todos.Where(x => x.IsCompleted).CountAsync();
            
            var total = await _service.GetCount();
            var completed = await _service.GetCompletedCount();
            
            var result = new TodoListStatus(){
                Total = total,
                Completed = completed
            };
            
            return result;
            
        }       
    }
}

source/complete/Yotodo/Views/Home/Index.cshtml
@model IEnumerable<Yotodo.Models.Todo>

<h1>Home Index</h1>

Nothing to see here


source/complete/Yotodo/Views/Shared/Components/TodoStatus/Default.cshtml
@model Yotodo.ViewModels.TodoListStatus

<span> Todos: @Model.Completed / @Model.Total</span>

source/complete/Yotodo/Views/Shared/_Layout.cshtml
@{
    var doComeBack = true;
}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Demo - yotodo</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">yotodo</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        
                        <li><a asp-controller="Todos" asp-action="Add" class="text-uppercase">Add Todo</a></li>
                        <li><a asp-controller="Todos" asp-action="Spa" class="text-uppercase">(Todo SPA)</a></li>
                       
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                         <li><p class="navbar-text navbar-right">  @await Component.InvokeAsync("TodoStatus", true) </p></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2016 - yotodo</p>
                <p><email>support</email></p>
                <div condition="doComeBack">
                    <p>
                        Please come back soon
                    </p>
                </div>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>

source/complete/Yotodo/Views/Todos/Add.cshtml
@model Yotodo.ViewModels.TodoAddViewModel

<h1>Add Todo</h1>

<div class="row">
 <form asp-controller="Todos" asp-action="Add" asp-route-returnurl="/" method="post" class="form-horizontal" role="form">
    <hr />
    <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Title" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Add Todo</button>
        </div>
    </div>
</form>
</div>

source/complete/Yotodo/Views/Todos/Index.cshtml
@model IEnumerable<Yotodo.Models.Todo>
@inject IStatisticsService StatsService

<div class="row">
    <div class="col-md-4">
        <h1>Task List</h1>
    </div>
    <div class="col-md-8">
       
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        
        <ul class="todo-list">
            @foreach (var t in Model){
                <li class="todo-list-item">
                    <input type="checkbox" id="@t.Id" checked="@t.IsCompleted"/> <label for="@t.Id">@t.Title</label>
                    <p>@t.Description </p>
                </li>
            }
        </ul>
        
        <br/>
        Total Items: @await StatsService.GetCount() Completed: @await StatsService.GetCompletedCount()
    </div>
</div>

source/complete/Yotodo/Views/Todos/spa.cshtml
<h1>Todo (SPA)</h1>

<div ng-app="app">
    <div ng-controller="TodoController as vm">
        
        <div class="row">
            <div class="col-md-12">
                 <ul class="todo-list">
                   
                        <li class="todo-list-item" ng-repeat="t in vm.items">
                            <input type="checkbox" ng-checked="t.isCompleted" ng-click="vm.complete(t)"/> <label ng-bind="t.title"></label>
                            <p ng-bind="t.description"></p>
                        </li>
                </ul>
            </div>
        </div>
        
         <hr />
        <div class="row">
            <h3>Add Todo</h3>
            <form class="form-horizontal" role="form" ng-submit="vm.add()">
               
               
                <div class="form-group">
                    <label for="Title" class="col-md-2 control-label">Title</label>
                    <div class="col-md-10">
                        <input id="Title" class="form-control" ng-model="vm.todo.title"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="Description" class="col-md-2 control-label">Description</label>
                    <div class="col-md-10">
                        <textarea id="Description" class="form-control" ng-model="vm.todo.description"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-primary">Add Todo</button>
                    </div>
                </div>
            </form>
        </div>
        
   </div>
   
</div>

@section scripts {
     <environment names="Development">
         
            <script type="text/javascript" src="~/lib/angular/angular.js"></script>
            <script type="text/javascript" src="~/js/angular/app.js"></script>
            <script type="text/javascript" src="~/js/angular/tasks.controller.js"></script>
            
        </environment>
        <environment names="Staging,Production">
            
            <script src="~/js/spa.min.js" asp-append-version="true"></script>
            
        </environment>
}